import { app, dialog, safeStorage, shell } from 'electron';
import path from 'node:path';
import { CreateJournal, UpdateJournal } from './application/save-journal';
import { registerHandlers } from './ipc/register-handlers';
import { MarkdownJournalRepository, recoverJournalResidues } from './infrastructure/markdown/journal-repository';
import { JsonProjectRepository } from './infrastructure/markdown/project-repository';
import { CredentialStore } from './infrastructure/credentials/credential-store';
import { ConfigureAi } from './application/configure-ai';
import { MarkdownReviewRepository } from './infrastructure/markdown/review-repository';
import { ReviewTaskManager } from './domain/review-task';
import { GenerateDailyReview } from './application/generate-daily-review';
import { GeneratePeriodicReview } from './application/generate-periodic-review';
import { DataTransferService } from './infrastructure/transfer/data-transfer-service';
import { DataDirectoryService } from './infrastructure/data-directory/data-directory-service';
import { DataRootConfig } from './infrastructure/data-directory/data-root-config';
import { DataRootHolder } from './infrastructure/data-directory/data-root-holder';
import { MarkdownProfileRepository } from './infrastructure/markdown/profile-repository';
import { GenerateInsightReview } from './application/generate-insight-review';
import { DailyAuditRecorder } from './skill-runtime/daily-audit-recorder';
import { VerifiedPatternRepository } from './infrastructure/patterns/verified-pattern-repository';
import { VerifiedPatternService } from './application/verified-patterns';
import { WebSearchService } from './infrastructure/web/web-search-service';
import { TemplateRepository } from './infrastructure/templates/template-repository';
import { AgentFacade } from './agent/agent-facade';
import { AgentModelTransport } from './agent/agent-model-transport';
import { ElectronAgentRuntime } from './agent/electron-agent-runtime';
import { AgentToolDispatcher } from './agent/agent-tool-dispatcher';
import { AgentMemorySearchService } from './agent/agent-memory-search-service';
import { MaintenanceCoordinator } from './infrastructure/lifecycle/maintenance-coordinator';
import type { IpcSourceGuard } from './ipc/ipc-source-guard';

export async function bootstrap(sourceGuard: IpcSourceGuard) {
  const config = new DataRootConfig();
  const loaded = await config.load();
  const maintenance = new MaintenanceCoordinator();
  const dataRootHolder = new DataRootHolder(config, loaded.dataRoot, maintenance);
  const dataRoot = dataRootHolder.get();
  const residueRecovery = await recoverJournalResidues(dataRoot);
  if (residueRecovery.conflicts.length || residueRecovery.ambiguous.length || residueRecovery.failed.length) {
    console.warn('知己日志残留未自动恢复：', JSON.stringify({ conflicts: residueRecovery.conflicts, ambiguous: residueRecovery.ambiguous, failed: residueRecovery.failed }));
  }
  const trashItem = (target: string) => shell.trashItem(target);
  const journals = new MarkdownJournalRepository(dataRoot, trashItem);
  const projects = new JsonProjectRepository(dataRoot, trashItem);
  const credentials = new CredentialStore(app.getPath('userData'), safeStorage);
  const configureAi = new ConfigureAi(dataRoot, credentials, !app.isPackaged);
  const reviews = new MarkdownReviewRepository(dataRoot, trashItem);
  const reviewTasks = new ReviewTaskManager();
  const profile = new MarkdownProfileRepository(dataRoot);
  const templates = new TemplateRepository(dataRoot);
  const createJournal = new CreateJournal(journals);
  const updateJournal = new UpdateJournal(journals);
  const generateDailyReview = new GenerateDailyReview(journals, reviews, configureAi, reviewTasks, undefined, profile, new DailyAuditRecorder(dataRoot));
  const generatePeriodicReview = new GeneratePeriodicReview(journals, reviews, configureAi, reviewTasks, undefined, profile);
  const generateInsightReview = new GenerateInsightReview(journals, reviews, configureAi, reviewTasks, undefined, profile);
  const verifiedPatterns = new VerifiedPatternService(reviews, new VerifiedPatternRepository(dataRoot), configureAi);
  const memorySearch = new AgentMemorySearchService(journals, reviews, verifiedPatterns);
  const webSearch = new WebSearchService();
  const transfer = new DataTransferService(dataRoot, app.getVersion());
  const dataDirectory = new DataDirectoryService(dataRoot, (target) => shell.openPath(target));
  const agentToolDispatcher = new AgentToolDispatcher({ journals, reviews, projects, verifiedPatterns, memorySearch, webSearch, createJournal, updateJournal, generateDailyReview, generatePeriodicReview, generateInsightReview, configureAi });
  const agentSessionRoot = path.join(dataRoot, 'agent', 'sessions');
  const agentFacade = new AgentFacade(new ElectronAgentRuntime({ sessionRoot: agentSessionRoot }), new AgentModelTransport(configureAi), agentToolDispatcher, { sessionRoot: agentSessionRoot, trashItem }, maintenance);
  maintenance.setLifecycle(agentFacade);
  registerHandlers({ journals, projects, reviews, profile, reviewTasks, generateDailyReview, generatePeriodicReview, generateInsightReview, verifiedPatterns, webSearch, templates, dataRootHolder, dataRootConfig: config, appVersion: app.getVersion(), createJournal, updateJournal, configureAi, transfer, dataDirectory, dialog, agentFacade, maintenance, sourceGuard, memorySearch });
  return { agentFacade };
}
